# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_swmm5', [dirname(__file__)])
        except ImportError:
            import _swmm5
            return _swmm5
        if fp is not None:
            try:
                _mod = imp.load_module('_swmm5', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _swmm5 = swig_import_helper()
    del swig_import_helper
else:
    import _swmm5
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def RunSwmmDll(*args):
  return _swmm5.RunSwmmDll(*args)
RunSwmmDll = _swmm5.RunSwmmDll

def OpenSwmmOutFile(*args):
  return _swmm5.OpenSwmmOutFile(*args)
OpenSwmmOutFile = _swmm5.OpenSwmmOutFile

def GetSwmmResult(*args):
  return _swmm5.GetSwmmResult(*args)
GetSwmmResult = _swmm5.GetSwmmResult

def CloseSwmmOutFile():
  return _swmm5.CloseSwmmOutFile()
CloseSwmmOutFile = _swmm5.CloseSwmmOutFile

def GetIDName():
  return _swmm5.GetIDName()
GetIDName = _swmm5.GetIDName

def InitGetIDName():
  return _swmm5.InitGetIDName()
InitGetIDName = _swmm5.InitGetIDName

def GetInt():
  return _swmm5.GetInt()
GetInt = _swmm5.GetInt
ERR_NONE = _swmm5.ERR_NONE
ERR_MEMORY = _swmm5.ERR_MEMORY
ERR_KINWAVE = _swmm5.ERR_KINWAVE
ERR_ODE_SOLVER = _swmm5.ERR_ODE_SOLVER
ERR_TIMESTEP = _swmm5.ERR_TIMESTEP
ERR_SUBCATCH_OUTLET = _swmm5.ERR_SUBCATCH_OUTLET
ERR_AQUIFER_PARAMS = _swmm5.ERR_AQUIFER_PARAMS
ERR_GROUND_ELEV = _swmm5.ERR_GROUND_ELEV
ERR_LENGTH = _swmm5.ERR_LENGTH
ERR_ELEV_DROP = _swmm5.ERR_ELEV_DROP
ERR_ROUGHNESS = _swmm5.ERR_ROUGHNESS
ERR_BARRELS = _swmm5.ERR_BARRELS
ERR_SLOPE = _swmm5.ERR_SLOPE
ERR_NO_XSECT = _swmm5.ERR_NO_XSECT
ERR_XSECT = _swmm5.ERR_XSECT
ERR_NO_CURVE = _swmm5.ERR_NO_CURVE
ERR_LOOP = _swmm5.ERR_LOOP
ERR_MULTI_OUTLET = _swmm5.ERR_MULTI_OUTLET
ERR_MULTI_DUMMY_LINK = _swmm5.ERR_MULTI_DUMMY_LINK
ERR_DIVIDER = _swmm5.ERR_DIVIDER
ERR_DIVIDER_LINK = _swmm5.ERR_DIVIDER_LINK
ERR_WEIR_DIVIDER = _swmm5.ERR_WEIR_DIVIDER
ERR_NODE_DEPTH = _swmm5.ERR_NODE_DEPTH
ERR_REGULATOR = _swmm5.ERR_REGULATOR
ERR_OUTFALL = _swmm5.ERR_OUTFALL
ERR_REGULATOR_SHAPE = _swmm5.ERR_REGULATOR_SHAPE
ERR_NO_OUTLETS = _swmm5.ERR_NO_OUTLETS
ERR_UNITHYD_TIMES = _swmm5.ERR_UNITHYD_TIMES
ERR_UNITHYD_RATIOS = _swmm5.ERR_UNITHYD_RATIOS
ERR_RDII_AREA = _swmm5.ERR_RDII_AREA
ERR_RAIN_FILE_CONFLICT = _swmm5.ERR_RAIN_FILE_CONFLICT
ERR_RAIN_GAGE_FORMAT = _swmm5.ERR_RAIN_GAGE_FORMAT
ERR_RAIN_GAGE_TSERIES = _swmm5.ERR_RAIN_GAGE_TSERIES
ERR_RAIN_GAGE_INTERVAL = _swmm5.ERR_RAIN_GAGE_INTERVAL
ERR_CYCLIC_TREATMENT = _swmm5.ERR_CYCLIC_TREATMENT
ERR_CURVE_SEQUENCE = _swmm5.ERR_CURVE_SEQUENCE
ERR_TIMESERIES_SEQUENCE = _swmm5.ERR_TIMESERIES_SEQUENCE
ERR_SNOWMELT_PARAMS = _swmm5.ERR_SNOWMELT_PARAMS
ERR_SNOWPACK_PARAMS = _swmm5.ERR_SNOWPACK_PARAMS
ERR_LID_TYPE = _swmm5.ERR_LID_TYPE
ERR_LID_LAYER = _swmm5.ERR_LID_LAYER
ERR_LID_PARAMS = _swmm5.ERR_LID_PARAMS
ERR_SUBCATCH_LID = _swmm5.ERR_SUBCATCH_LID
ERR_LID_AREAS = _swmm5.ERR_LID_AREAS
ERR_LID_CAPTURE_AREA = _swmm5.ERR_LID_CAPTURE_AREA
ERR_START_DATE = _swmm5.ERR_START_DATE
ERR_REPORT_DATE = _swmm5.ERR_REPORT_DATE
ERR_REPORT_STEP = _swmm5.ERR_REPORT_STEP
ERR_INPUT = _swmm5.ERR_INPUT
ERR_LINE_LENGTH = _swmm5.ERR_LINE_LENGTH
ERR_ITEMS = _swmm5.ERR_ITEMS
ERR_KEYWORD = _swmm5.ERR_KEYWORD
ERR_DUP_NAME = _swmm5.ERR_DUP_NAME
ERR_NAME = _swmm5.ERR_NAME
ERR_NUMBER = _swmm5.ERR_NUMBER
ERR_DATETIME = _swmm5.ERR_DATETIME
ERR_RULE = _swmm5.ERR_RULE
ERR_TRANSECT_UNKNOWN = _swmm5.ERR_TRANSECT_UNKNOWN
ERR_TRANSECT_SEQUENCE = _swmm5.ERR_TRANSECT_SEQUENCE
ERR_TRANSECT_TOO_FEW = _swmm5.ERR_TRANSECT_TOO_FEW
ERR_TRANSECT_TOO_MANY = _swmm5.ERR_TRANSECT_TOO_MANY
ERR_TRANSECT_MANNING = _swmm5.ERR_TRANSECT_MANNING
ERR_TRANSECT_OVERBANK = _swmm5.ERR_TRANSECT_OVERBANK
ERR_TRANSECT_NO_DEPTH = _swmm5.ERR_TRANSECT_NO_DEPTH
ERR_TREATMENT_EXPR = _swmm5.ERR_TREATMENT_EXPR
ERR_FILE_NAME = _swmm5.ERR_FILE_NAME
ERR_INP_FILE = _swmm5.ERR_INP_FILE
ERR_RPT_FILE = _swmm5.ERR_RPT_FILE
ERR_OUT_FILE = _swmm5.ERR_OUT_FILE
ERR_OUT_WRITE = _swmm5.ERR_OUT_WRITE
ERR_OUT_READ = _swmm5.ERR_OUT_READ
ERR_RAIN_FILE_SCRATCH = _swmm5.ERR_RAIN_FILE_SCRATCH
ERR_RAIN_FILE_OPEN = _swmm5.ERR_RAIN_FILE_OPEN
ERR_RAIN_FILE_DATA = _swmm5.ERR_RAIN_FILE_DATA
ERR_RAIN_FILE_SEQUENCE = _swmm5.ERR_RAIN_FILE_SEQUENCE
ERR_RAIN_FILE_FORMAT = _swmm5.ERR_RAIN_FILE_FORMAT
ERR_RAIN_FILE_GAGE = _swmm5.ERR_RAIN_FILE_GAGE
ERR_RUNOFF_FILE_OPEN = _swmm5.ERR_RUNOFF_FILE_OPEN
ERR_RUNOFF_FILE_FORMAT = _swmm5.ERR_RUNOFF_FILE_FORMAT
ERR_RUNOFF_FILE_END = _swmm5.ERR_RUNOFF_FILE_END
ERR_RUNOFF_FILE_READ = _swmm5.ERR_RUNOFF_FILE_READ
ERR_HOTSTART_FILE_NAMES = _swmm5.ERR_HOTSTART_FILE_NAMES
ERR_HOTSTART_FILE_OPEN = _swmm5.ERR_HOTSTART_FILE_OPEN
ERR_HOTSTART_FILE_FORMAT = _swmm5.ERR_HOTSTART_FILE_FORMAT
ERR_HOTSTART_FILE_READ = _swmm5.ERR_HOTSTART_FILE_READ
ERR_NO_CLIMATE_FILE = _swmm5.ERR_NO_CLIMATE_FILE
ERR_CLIMATE_FILE_OPEN = _swmm5.ERR_CLIMATE_FILE_OPEN
ERR_CLIMATE_FILE_READ = _swmm5.ERR_CLIMATE_FILE_READ
ERR_CLIMATE_END_OF_FILE = _swmm5.ERR_CLIMATE_END_OF_FILE
ERR_RDII_FILE_SCRATCH = _swmm5.ERR_RDII_FILE_SCRATCH
ERR_RDII_FILE_OPEN = _swmm5.ERR_RDII_FILE_OPEN
ERR_RDII_FILE_FORMAT = _swmm5.ERR_RDII_FILE_FORMAT
ERR_ROUTING_FILE_OPEN = _swmm5.ERR_ROUTING_FILE_OPEN
ERR_ROUTING_FILE_FORMAT = _swmm5.ERR_ROUTING_FILE_FORMAT
ERR_ROUTING_FILE_NOMATCH = _swmm5.ERR_ROUTING_FILE_NOMATCH
ERR_ROUTING_FILE_NAMES = _swmm5.ERR_ROUTING_FILE_NAMES
ERR_TABLE_FILE_OPEN = _swmm5.ERR_TABLE_FILE_OPEN
ERR_TABLE_FILE_READ = _swmm5.ERR_TABLE_FILE_READ
ERR_SYSTEM = _swmm5.ERR_SYSTEM
ERR_NOT_CLOSED = _swmm5.ERR_NOT_CLOSED
ERR_NOT_OPEN = _swmm5.ERR_NOT_OPEN
ERR_FILE_SIZE = _swmm5.ERR_FILE_SIZE
MAXERRMSG = _swmm5.MAXERRMSG

def error_getMsg(*args):
  return _swmm5.error_getMsg(*args)
error_getMsg = _swmm5.error_getMsg

def error_getCode(*args):
  return _swmm5.error_getCode(*args)
error_getCode = _swmm5.error_getCode

def error_setInpError(*args):
  return _swmm5.error_setInpError(*args)
error_setInpError = _swmm5.error_setInpError
# This file is compatible with both classic and new-style classes.

cvar = _swmm5.cvar

